# Generated by Django 5.2.8 on 2026-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="created_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="endDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="startDate",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked-in", "Checked In"),
                    ("checked-out", "Checked Out"),
                    ("unconfirmed", "Unconfirmed"),
                ],
                db_index=True,
                default="unconfirmed",
            ),
        ),
        migrations.AlterField(
            model_name="cabins",
            name="discount",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="guests",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="guests",
            name="fullName",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="guests",
            name="nationalID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="guests",
            index=models.Index(
                fields=["email"],
                include=(
                    "fullName",
                    "hotel",
                    "nationalID",
                    "nationality",
                    "countryFlag",
                ),
                name="guest_email_lookup_idx",
            ),
        ),
    ]
