# Generated by Django 5.2.8 on 2026-04-24 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_bookings_created_at_alter_bookings_enddate_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bookings",
            index=models.Index(
                fields=["created_at"],
                include=("totalPrice",),
                name="booking_date_metrics_idx",
            ),
        ),
    ]
