# Generated by Django 5.2.8 on 2026-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bookings_booking_date_metrics_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="guests",
            name="isOAuthUser",
            field=models.BooleanField(default=False),
        ),
    ]
