# Generated by Django 5.2.8 on 2026-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_guests_isoauthuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="guests",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
