# Generated by Django 5.2.8 on 2026-03-29 19:58

import api.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.TextField()),
                (
                    "maxCapacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("regularPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("observations", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabins",
                        to="users.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cabins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("mark_clean", "Can mark room as cleaned"),
                    ("assign_room", "Can assign room to booking"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Guests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, db_index=True)),
                ("fullName", models.TextField(db_index=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "nationalID",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("nationality", models.TextField(blank=True, null=True)),
                (
                    "countryFlag",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        validators=[api.validators.validate_secure_image_url],
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="users.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(db_index=True)),
                ("startDate", models.DateField(db_index=True)),
                ("endDate", models.DateField(db_index=True)),
                (
                    "numNights",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "numGuests",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("cabinPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "extrasPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("totalPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked-in", "Checked In"),
                            ("checked-out", "Checked Out"),
                            ("unconfirmed", "Unconfirmed"),
                        ],
                        default="unconfirmed",
                    ),
                ),
                ("isPaid", models.BooleanField(default=False)),
                ("observations", models.TextField(blank=True, max_length=500)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="users.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cabin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="api.cabins",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="api.guests",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("checkin_guest", "Can check in guest"),
                    ("checkout_guest", "Can check out guest"),
                    ("cancel_booking", "Can cancel booking"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, db_index=True)),
                ("minBookingLength", models.IntegerField()),
                ("maxBookingLength", models.IntegerField()),
                ("minGuestsPerBooking", models.IntegerField()),
                (
                    "breakfastPrice",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="users.hotel",
                    ),
                ),
            ],
        ),
    ]
