# Generated by Django 5.2.8 on 2026-01-12 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(db_index=True)),
                ("startDate", models.DateField(db_index=True)),
                ("endDate", models.DateField(db_index=True)),
                (
                    "numNights",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "numGuests",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("cabinPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "extrasPrice",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("totalPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                ("status", models.CharField(default="unconfirmed")),
                ("isPaid", models.BooleanField()),
                ("observations", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("checkin_guest", "Can check in guest"),
                    ("checkout_guest", "Can check out guest"),
                    ("cancel_booking", "Can cancel booking"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cabins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.TextField()),
                (
                    "maxCapacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(2),
                        ]
                    ),
                ),
                ("regularPrice", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("observations", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="users/%Y/%m/%d")),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("mark_clean", "Can mark room as cleaned"),
                    ("assign_room", "Can assign room to booking"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Guests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, db_index=True)),
                ("fullName", models.TextField(db_index=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("nationalID", models.BigIntegerField(db_index=True)),
                ("nationality", models.TextField()),
                (
                    "countryFlag",
                    models.ImageField(blank=True, upload_to="users/%Y/%m/%d"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("startDate", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                (
                    "staffCapacity",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="defaults/low-light.png",
                        null=True,
                        upload_to="hotels/logos/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, db_index=True)),
                ("minBookingLength", models.IntegerField()),
                ("maxBookingLength", models.IntegerField()),
                ("minGuestsPerBooking", models.IntegerField()),
                (
                    "breakfastPrice",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
            ],
        ),
    ]
