# Generated by Django 5.2.8 on 2026-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_bookings_created_at_alter_bookings_startdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="startDate",
            field=models.DateField(db_index=True),
        ),
    ]
