# Generated by Django 5.2.8 on 2026-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="nationalID",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="guests",
            name="nationality",
            field=models.TextField(blank=True, null=True),
        ),
    ]
