# Generated by Django 5.2.8 on 2026-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_bookings_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="created_at",
            field=models.DateField(db_index=True),
        ),
    ]
