# Generated by Django 5.2.8 on 2026-03-13 04:52

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_guests_nationalid_alter_guests_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guests",
            name="countryFlag",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                validators=[api.validators.validate_secure_image_url],
            ),
        ),
    ]
