# Generated by Django 5.2.8 on 2026-03-15 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_guests_countryflag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="observations",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="status",
            field=models.CharField(
                choices=[
                    ("checked-in", "Checked In"),
                    ("checked-out", "Checked Out"),
                    ("unconfirmed", "Unconfirmed"),
                ],
                default="unconfirmed",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_handled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
